import { useState } from "react";
import { useContract } from "@/providers/contract-provider";
import { FINANCIER_ID } from "@/lib/demo-seed";
import { bytesToHex, hexToBytes, truncateHex } from "@/lib/hex";
import { entriesOf } from "@/lib/ledger";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Alert, AlertDescription } from "@/components/ui/alert";

const STATUS_LABEL = ["No commitment", "Reserved", "Settled"] as const;

export function FinancierDashboard() {
  const { contractAddress, ledgerState } = useContract();
  const [lookup, setLookup] = useState("");

  if (!contractAddress || !ledgerState) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>No deployed policy yet</CardTitle>
          <CardDescription>Waiting for the exporter to deploy a financing policy.</CardDescription>
        </CardHeader>
      </Card>
    );
  }

  const policy = ledgerState.policy;
  const myRequests = entriesOf(ledgerState.commitments).filter(
    ([, commitment]) => bytesToHex(commitment.requesterId) === bytesToHex(FINANCIER_ID),
  );

  let lookupResult: { found: boolean; status?: string } | null = null;
  if (lookup.trim()) {
    try {
      const key = hexToBytes(lookup.trim());
      if (ledgerState.commitments.member(key)) {
        const c = ledgerState.commitments.lookup(key);
        lookupResult = { found: true, status: STATUS_LABEL[c.status] };
      } else {
        lookupResult = { found: false };
      }
    } catch {
      lookupResult = null;
    }
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Policy in effect</CardTitle>
          <CardDescription className="font-mono text-xs break-all">
            {bytesToHex(policy.policyId)} · v{policy.version.toString()}
          </CardDescription>
        </CardHeader>
        <CardContent className="text-sm space-y-1">
          <p>
            Verified against this policy: at least {policy.minimumCampaigns.toString()} campaigns of
            history, and a request no larger than {policy.maxRatioNumerator.toString()}/
            {policy.ratioDenominator.toString()} of the producer&apos;s estimated harvest settlement.
          </p>
          <p className="text-muted-foreground">
            Evidence is valid, current, and issued by authorized organizations — the underlying production
            and financial figures are never disclosed to this dashboard.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Requests addressed to this financier</CardTitle>
          <CardDescription>
            Eligibility proofs are generated by the producer holding their own evidence; this dashboard
            shows the outcome of requests naming this financier as the requester, without ever seeing the
            underlying credential.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {myRequests.length === 0 ? (
            <p className="text-sm text-muted-foreground">No requests yet.</p>
          ) : (
            <table className="w-full text-sm">
              <thead className="text-left text-muted-foreground">
                <tr>
                  <th className="pb-1 font-normal">Nullifier</th>
                  <th className="pb-1 font-normal">Status</th>
                  <th className="pb-1 font-normal">Requested</th>
                  <th className="pb-1 font-normal">Issuer</th>
                </tr>
              </thead>
              <tbody>
                {myRequests.map(([nullifier, commitment]) => (
                  <tr key={bytesToHex(nullifier)} className="border-t">
                    <td className="py-1.5 font-mono text-xs">{truncateHex(bytesToHex(nullifier))}</td>
                    <td className="py-1.5">
                      <Badge variant={commitment.status === 2 ? "secondary" : "default"}>
                        {STATUS_LABEL[commitment.status]}
                      </Badge>
                    </td>
                    <td className="py-1.5">{commitment.requestedValue.toString()}</td>
                    <td className="py-1.5 font-mono text-xs">{truncateHex(bytesToHex(commitment.issuerId))}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Verify a nullifier / commitment</CardTitle>
          <CardDescription>Paste a campaign nullifier to check its registered status directly against chain state.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <Input placeholder="0x…" value={lookup} onChange={(e) => setLookup(e.target.value)} />
          {lookupResult && (
            <Alert variant={lookupResult.found ? "success" : "warning"}>
              <AlertDescription>
                {lookupResult.found
                  ? `Registered — status: ${lookupResult.status}`
                  : "No commitment is registered under this nullifier."}
              </AlertDescription>
            </Alert>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Issuer set</CardTitle>
          <CardDescription>Organizations authorized to sign productive evidence for this policy.</CardDescription>
        </CardHeader>
        <CardContent>
          {ledgerState.issuers.isEmpty() ? (
            <p className="text-sm text-muted-foreground">No issuers registered.</p>
          ) : (
            <div className="flex flex-wrap gap-2">
              {entriesOf(ledgerState.issuers).map(([id, record]) => (
                <Badge key={bytesToHex(id)} variant={record.active ? "secondary" : "destructive"}>
                  {truncateHex(bytesToHex(id))} · {record.active ? "valid" : "revoked"}
                </Badge>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
