/**
 * Off-chain issuer signing for Proof of Harvest.
 *
 * This is what an exporter's or certifier's backend does when it attests a
 * producer's productive credential: it Schnorr-signs the credential over the
 * Jubjub curve so the circuit can verify the attestation came from a key
 * registered in the on-chain issuer registry.
 *
 * Deliberate design choice: every curve and hash operation is delegated to the
 * contract's own `pureCircuits`, not reimplemented here. `deriveIssuerPublicKey`
 * is `ecMulGenerator` and `schnorrChallenge3` is the same `transientHash` over
 * the same struct layout that `schnorrVerify` recomputes in-circuit. A
 * hand-rolled TypeScript Jubjub implementation could disagree with the compiled
 * circuit on curve parameters, point encoding or hash field ordering; this
 * cannot. The only arithmetic done here is `bigint` modular arithmetic in the
 * scalar field, which the circuit cannot do (Compact has no division).
 */

import { createHash } from 'node:crypto';
import {
  pureCircuits,
  type CampaignCredential,
  type Schnorr_SchnorrSignature,
} from './managed/ProofOfHarvest/contract/index.js';

/**
 * Order of the prime-order subgroup generated by Jubjub's generator, i.e. the
 * modulus the Schnorr response must be reduced by.
 *
 * Verified empirically against the compiled circuit rather than taken on faith:
 * the compiled runtime rejects any response that does not decode as an
 * `EmbeddedFr` element, and signatures reduced modulo this value verify while
 * signatures reduced modulo the full group order (8L) or the BLS12-381 scalar
 * field are rejected outright. See `contract/spike/` for the probe.
 */
export const JUBJUB_SUBGROUP_ORDER =
  6554484396890773809930967563523245729705921265872317281365359162392183254199n;

/**
 * 2^248. `schnorrVerify` truncates its 255-bit challenge hash to 248 bits so
 * the challenge is guaranteed to be a valid Jubjub scalar; the signer must
 * apply the identical reduction or the verification equation will not close.
 */
export const TWO_248 = 1n << 248n;

export interface IssuerKeyPair {
  /** Jubjub scalar. Never leaves the issuer's backend. */
  readonly secretScalar: bigint;
  readonly publicKey: { readonly x: bigint; readonly y: bigint };
}

const mod = (value: bigint, modulus: bigint): bigint => {
  const remainder = value % modulus;
  return remainder < 0n ? remainder + modulus : remainder;
};

const bytesToBigIntLE = (bytes: Uint8Array): bigint => {
  let acc = 0n;
  for (let i = bytes.length - 1; i >= 0; i -= 1) {
    acc = (acc << 8n) | BigInt(bytes[i]!);
  }
  return acc;
};

/**
 * Derives an issuer key pair from a seed string.
 *
 * Test and demo helper only. A real issuer generates its scalar from a CSPRNG
 * and keeps it in an HSM or KMS; deriving it from a human-readable seed makes
 * the key guessable.
 */
export const issuerKeyPairFromSeed = (seed: string): IssuerKeyPair => {
  const digest = createHash('sha512').update(`poh:issuer-seed:v1:${seed}`).digest();
  const secretScalar = mod(bytesToBigIntLE(digest), JUBJUB_SUBGROUP_ORDER);
  if (secretScalar === 0n) {
    throw new Error('issuerKeyPairFromSeed: seed produced a zero scalar; use another seed');
  }
  return {
    secretScalar,
    publicKey: pureCircuits.deriveIssuerPublicKey(secretScalar),
  };
};

/**
 * Deterministic per-signature nonce, RFC 6979 in spirit.
 *
 * Schnorr nonce reuse across two different messages leaks the secret scalar
 * outright, so the nonce is derived from the secret and the message rather than
 * being left to the caller. That also makes signatures reproducible, which
 * keeps tests deterministic.
 */
const deterministicNonce = (secretScalar: bigint, message: readonly bigint[]): bigint => {
  const hash = createHash('sha512');
  hash.update('poh:schnorr-nonce:v1');
  hash.update(secretScalar.toString(16).padStart(64, '0'));
  for (const limb of message) {
    hash.update(limb.toString(16).padStart(64, '0'));
  }
  const nonce = mod(bytesToBigIntLE(hash.digest()), JUBJUB_SUBGROUP_ORDER);
  // A zero nonce would publish the announcement as the identity point and leak
  // the secret; astronomically unlikely, but cheap to exclude.
  return nonce === 0n ? 1n : nonce;
};

/** Signs an already-built 3-element message vector. */
const signMessage = (
  secretScalar: bigint,
  message: readonly bigint[],
): Schnorr_SchnorrSignature => {
  if (message.length !== 3) {
    throw new Error(`signMessage: expected a 3-element message, got ${message.length}`);
  }
  const publicKey = pureCircuits.deriveIssuerPublicKey(secretScalar);
  const nonce = deterministicNonce(secretScalar, message);
  const announcement = pureCircuits.deriveIssuerPublicKey(nonce);

  const fullChallenge = pureCircuits.schnorrChallenge3(
    announcement.x,
    announcement.y,
    publicKey.x,
    publicKey.y,
    [...message],
  );
  const challenge = fullChallenge % TWO_248;

  // response = nonce + challenge * secret, reduced into the subgroup order.
  // The circuit verifies response*G == announcement + challenge*publicKey,
  // which only holds if this reduction uses the subgroup order.
  const response = mod(nonce + challenge * secretScalar, JUBJUB_SUBGROUP_ORDER);
  return { announcement, response };
};

/**
 * Signs a productive credential, binding it to a specific deployed policy.
 *
 * Binding `policyHash` into the signed message means a credential attested for
 * one policy version cannot be replayed against a different policy.
 */
export const signCredential = (
  issuer: IssuerKeyPair,
  credential: CampaignCredential,
  policyHash: Uint8Array,
): Schnorr_SchnorrSignature =>
  signMessage(issuer.secretScalar, pureCircuits.credentialMessage(credential, policyHash));

/**
 * Signs an authorization to settle a specific registered campaign.
 *
 * Uses a different domain tag from `signCredential`, so a credential signature
 * can never be replayed as a settlement authorization or vice versa.
 */
export const signSettlement = (
  issuer: IssuerKeyPair,
  nullifier: Uint8Array,
  policyHash: Uint8Array,
): Schnorr_SchnorrSignature =>
  signMessage(issuer.secretScalar, pureCircuits.settlementMessage(nullifier, policyHash));
